apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: find-unclaimed-court-money-ingress
  namespace: find-unclaimed-court-money-dev
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: find-unclaimed-court-money-ingress-find-unclaimed-court-money-dev-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: app-secrets
spec:
  tls:
  - hosts:
    - dev.find-unclaimed-court-money.service.justice.gov.uk
    secretName: find-unclaimed-court-money-cert
  rules:
  - host: dev.find-unclaimed-court-money.service.justice.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: find-unclaimed-court-money-service
            port:
              number: 3000
